/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    'speaker-categories': SpeakerCategory;
    speakers: Speaker;
    'partnership-types': PartnershipType;
    partners: Partner;
    'press-articles': PressArticle;
    users: User;
    'partnership-submissions': PartnershipSubmission;
    'contact-submissions': ContactSubmission;
    'newsletter-submissions': NewsletterSubmission;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'speaker-categories': SpeakerCategoriesSelect<false> | SpeakerCategoriesSelect<true>;
    speakers: SpeakersSelect<false> | SpeakersSelect<true>;
    'partnership-types': PartnershipTypesSelect<false> | PartnershipTypesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'press-articles': PressArticlesSelect<false> | PressArticlesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'partnership-submissions': PartnershipSubmissionsSelect<false> | PartnershipSubmissionsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'newsletter-submissions': NewsletterSubmissionsSelect<false> | NewsletterSubmissionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ar') | ('en' | 'ar')[];
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | EventHeroBlock
    | StatsBlockType
    | BentoGridBlock
    | HighlightsBlockType
    | SpeakersBlockType
    | SpeakerHighlightBlockType
    | FullSpeakersBlockType
    | ProgramBlock
    | PartnersBlock
    | PartnersGridBlockType
    | PartnerCtaBlockType
    | PromoBannerBlock
    | PressBlock
    | PageBannerBlock
    | GalleryBlock
    | EventHighlightsBlockType
    | AboutBlockType
    | EventAgendaBlockType
    | AllPostsBlockType
    | TextCardBlock
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | VenueHeroBlockType
    | VenueBentoBlockType
    | FullWidthImageBlockType
    | LocationBlockType
    | PartnerFormBlockType
    | ContactBlockType
    | AllPressBlockType
    | CtaButtonBlockType
    | CtaBannerBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  author?: string | null;
  /**
   * Show this post as the featured post at the top of the blog listing.
   */
  featured?: boolean | null;
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventHeroBlock".
 */
export interface EventHeroBlock {
  /**
   * Upload an .mp4 to use as the looping background video.
   */
  backgroundVideo?: (number | null) | Media;
  subtitle?: string | null;
  poweredByLabel?: string | null;
  poweredByLogo?: (number | null) | Media;
  eventDate: string;
  venue: string;
  showCountdown?: boolean | null;
  /**
   * The countdown timer will count down to this date.
   */
  countdownDate?: string | null;
  countdownLabel?: string | null;
  ctaLink: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlockType".
 */
export interface StatsBlockType {
  heading?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BentoGridBlock".
 */
export interface BentoGridBlock {
  cells?:
    | {
        title?: string | null;
        description?: string | null;
        /**
         * Optional background image for this cell
         */
        media?: (number | null) | Media;
        cellSize: 'threeCol' | 'oneThird' | 'fiveCol' | 'half' | 'sevenCol';
        /**
         * Light = light beige bg, Warm = tan/gold bg, Image Overlay = dark text over image, Video (click to play) = thumbnail with play button, Video (autoplay) = video plays inline muted
         */
        style: 'light' | 'warm' | 'overlay' | 'video' | 'videoAutoplay';
        /**
         * Video file. For "click to play" it opens in a lightbox; for autoplay it plays inline.
         */
        video?: (number | null) | Media;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'bentoGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HighlightsBlockType".
 */
export interface HighlightsBlockType {
  heading?: string | null;
  cards?:
    | {
        /**
         * SVG or small icon image
         */
        icon: number | Media;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  tagline?: string | null;
  enableLink?: boolean | null;
  link?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'highlightsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpeakersBlockType".
 */
export interface SpeakersBlockType {
  heading?: string | null;
  /**
   * Pick the speakers to feature and drag to reorder. Leave empty to show all speakers (sorted by their order field).
   */
  selectedSpeakers?: (number | Speaker)[] | null;
  description?: string | null;
  enableLink?: boolean | null;
  link?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'speakersBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers".
 */
export interface Speaker {
  id: number;
  name: string;
  /**
   * e.g. "Executive Chairman & Founder AEON Clinic"
   */
  title: string;
  photo: number | Media;
  /**
   * Assign one or more categories to group this speaker in the speakers grid
   */
  category?: (number | SpeakerCategory)[] | null;
  /**
   * Display order within category (lower numbers appear first)
   */
  order?: number | null;
  /**
   * Short bio shown on the card flip (1-2 sentences)
   */
  bio?: string | null;
  /**
   * Full biography shown on the speaker detail page
   */
  longBio?: string | null;
  /**
   * e.g. "https://linkedin.com/in/speaker-name"
   */
  linkedinUrl?: string | null;
  /**
   * Build the speaker detail page content
   */
  layout?: (ContentBlock | MediaBlock | CallToActionBlock | BannerBlock | CodeBlock)[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speaker-categories".
 */
export interface SpeakerCategory {
  id: number;
  title: string;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpeakerHighlightBlockType".
 */
export interface SpeakerHighlightBlockType {
  speaker: number | Speaker;
  /**
   * Optional override for the role shown under the speaker's name. Leave empty to use the speaker's default title.
   */
  roleLabel?: string | null;
  /**
   * Optional override for the speaker image. Leave empty to use the speaker's default photo.
   */
  photoOverride?: (number | null) | Media;
  quote: string;
  heading: string;
  /**
   * Paragraphs separated by blank lines
   */
  body: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'speakerHighlightBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FullSpeakersBlockType".
 */
export interface FullSpeakersBlockType {
  heading?: string | null;
  description?: string | null;
  /**
   * Leave empty to show all categories.
   */
  displayCategories?: (number | SpeakerCategory)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'fullSpeakersBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProgramBlock".
 */
export interface ProgramBlock {
  title: string;
  description?: string | null;
  backgroundImage?: (number | null) | Media;
  tabs: {
    label: string;
    themeTitle?: string | null;
    items?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'programBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersBlock".
 */
export interface PartnersBlock {
  title: string;
  description?: string | null;
  /**
   * Which types of partners to display in the main grid.
   */
  partnershipTypes: (number | PartnershipType)[];
  enableCTA?: boolean | null;
  link?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
  };
  strategicPartnersHeading?: string | null;
  strategicPartners?: (number | Partner)[] | null;
  poweredByText?: string | null;
  poweredByLogo?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partnersBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnership-types".
 */
export interface PartnershipType {
  id: number;
  name: string;
  /**
   * URL-friendly identifier (e.g. "sponsor", "exhibitor")
   */
  slug: string;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo: number | Media;
  /**
   * Optional external link. If set, the partner's logo becomes clickable and opens this URL in a new tab.
   */
  website?: string | null;
  /**
   * A company can hold multiple partnership types simultaneously.
   */
  partnershipTypes: (number | PartnershipType)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersGridBlockType".
 */
export interface PartnersGridBlockType {
  heading?: string | null;
  /**
   * Select which partnership types to display. Each type will be shown as a separate section.
   */
  partnershipTypes?: (number | PartnershipType)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partnersGridBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnerCtaBlockType".
 */
export interface PartnerCtaBlockType {
  title: string;
  description?: string | null;
  link: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'partnerCtaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromoBannerBlock".
 */
export interface PromoBannerBlock {
  /**
   * Event logo (white, transparent PNG)
   */
  logo?: (number | null) | Media;
  /**
   * e.g. "7th – 10th November 2026"
   */
  dateText: string;
  /**
   * Venue logo/name image (white, transparent PNG)
   */
  venueImage?: (number | null) | Media;
  ctaLink: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'promoBannerBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PressBlock".
 */
export interface PressBlock {
  title: string;
  description?: string | null;
  enableTopLink?: boolean | null;
  topLink?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
  };
  /**
   * Cards shown below the press grid (e.g. "Previous edition", "Blog")
   */
  bottomCards?:
    | {
        title: string;
        description?: string | null;
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pressBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageBannerBlock".
 */
export interface PageBannerBlock {
  backgroundImage: number | Media;
  /**
   * e.g. "PREVIOUS EDITION"
   */
  subtitle?: string | null;
  title: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageBannerBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  items: {
    media: number | Media;
    wide?: boolean | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'galleryBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventHighlightsBlockType".
 */
export interface EventHighlightsBlockType {
  heading: string;
  bulletPoints?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  featuredImage: number | Media;
  galleryImages?:
    | {
        media: number | Media;
        id?: string | null;
      }[]
    | null;
  enableLink?: boolean | null;
  link?: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventHighlightsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlockType".
 */
export interface AboutBlockType {
  sections?:
    | {
        heading: string;
        /**
         * Use blank lines to separate paragraphs.
         */
        body: string;
        image: number | Media;
        imagePosition?: ('right' | 'left') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'aboutBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventAgendaBlockType".
 */
export interface EventAgendaBlockType {
  subtitleLeft?: string | null;
  subtitleRight?: string | null;
  pdfDownload?: (number | null) | Media;
  pdfButtonLabel?: string | null;
  days: {
    label: string;
    date: string;
    title: string;
    theme?: string | null;
    moderator?: string | null;
    sessions: {
      isTheme?: boolean | null;
      themeText?: string | null;
      timeStart?: string | null;
      timeEnd?: string | null;
      isBreak?: boolean | null;
      showTime?: boolean | null;
      moderator?: string | null;
      content?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      id?: string | null;
    }[];
    tracks?:
      | {
          name: string;
          title: string;
          moderator?: string | null;
          sessions: {
            isTheme?: boolean | null;
            themeText?: string | null;
            timeStart?: string | null;
            timeEnd?: string | null;
            isBreak?: boolean | null;
            showTime?: boolean | null;
            moderator?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
          }[];
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventAgendaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AllPostsBlockType".
 */
export interface AllPostsBlockType {
  /**
   * Number of posts per page (default 6)
   */
  perPage?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'allPostsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextCardBlock".
 */
export interface TextCardBlock {
  heading: string;
  /**
   * Paragraphs separated by blank lines
   */
  body: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textCardBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VenueHeroBlockType".
 */
export interface VenueHeroBlockType {
  backgroundImage: number | Media;
  /**
   * Logo or overlay image positioned on the left side of the hero.
   */
  overlayImage?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'venueHeroBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VenueBentoBlockType".
 */
export interface VenueBentoBlockType {
  cards: {
    colSpan: '1' | '2' | '3';
    cardType: 'imageWithGradient' | 'imageOnly' | 'imageWithText' | 'textOnly';
    backgroundImage?: (number | null) | Media;
    title?: string | null;
    description?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'venueBentoBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FullWidthImageBlockType".
 */
export interface FullWidthImageBlockType {
  image: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'fullWidthImageBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocationBlockType".
 */
export interface LocationBlockType {
  title: string;
  description?: string | null;
  /**
   * Map or location image.
   */
  image: number | Media;
  /**
   * Link URL for the map image (e.g. Google Maps link).
   */
  imageLink?: string | null;
  cards?:
    | {
        title: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'locationBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnerFormBlockType".
 */
export interface PartnerFormBlockType {
  title: string;
  subtitle?: string | null;
  descriptionLeft?: string | null;
  descriptionRight?: string | null;
  formTitle?: string | null;
  /**
   * Configure benefits text for each partnership type.
   */
  types: {
    value: 'sponsor' | 'partner' | 'speaker' | 'other';
    benefitsTitle: string;
    benefitsDescription?: string | null;
    id?: string | null;
  }[];
  submitButtonText?: string | null;
  successTitle?: string | null;
  successMessage?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partnerFormBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlockType".
 */
export interface ContactBlockType {
  detailsTitle: string;
  detailsDescription?: string | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  image?: (number | null) | Media;
  formTitle?: string | null;
  submitButtonText?: string | null;
  successTitle?: string | null;
  successMessage?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AllPressBlockType".
 */
export interface AllPressBlockType {
  /**
   * Number of articles per page (default 6)
   */
  perPage?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'allPressBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaButtonBlockType".
 */
export interface CtaButtonBlockType {
  link: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
  };
  alignment?: ('left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaButtonBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock".
 */
export interface CtaBannerBlock {
  backgroundImage: number | Media;
  /**
   * Use line breaks to wrap the title across multiple lines.
   */
  title: string;
  subtitle?: string | null;
  ctaLink: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
    /**
     * Choose how the link should be rendered.
     */
    appearance?: ('default' | 'outline') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBannerBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-articles".
 */
export interface PressArticle {
  id: number;
  title: string;
  /**
   * e.g. "Gulf Today", "Khaleej Times"
   */
  publicationName: string;
  /**
   * Publication logo (transparent PNG)
   */
  publicationLogo: number | Media;
  /**
   * Link to the external press article
   */
  externalUrl: string;
  date: string;
  thumbnail: number | Media;
  /**
   * Show this article as the featured press article.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlockType".
 */
export interface FAQBlockType {
  title: string;
  subtitle?: string | null;
  description?: string | null;
  faqs: {
    question: string;
    answer: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    defaultOpen?: boolean | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqBlock';
}

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnership-submissions".
 */
export interface PartnershipSubmission {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  companyName: string;
  type?: ('sponsor' | 'partner' | 'speaker' | 'other') | null;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-submissions".
 */
export interface NewsletterSubmission {
  id: number;
  email: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'speaker-categories';
        value: number | SpeakerCategory;
      } | null)
    | ({
        relationTo: 'speakers';
        value: number | Speaker;
      } | null)
    | ({
        relationTo: 'partnership-types';
        value: number | PartnershipType;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'press-articles';
        value: number | PressArticle;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'partnership-submissions';
        value: number | PartnershipSubmission;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'newsletter-submissions';
        value: number | NewsletterSubmission;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        eventHero?: T | EventHeroBlockSelect<T>;
        statsBlock?: T | StatsBlockTypeSelect<T>;
        bentoGrid?: T | BentoGridBlockSelect<T>;
        highlightsBlock?: T | HighlightsBlockTypeSelect<T>;
        speakersBlock?: T | SpeakersBlockTypeSelect<T>;
        speakerHighlightBlock?: T | SpeakerHighlightBlockTypeSelect<T>;
        fullSpeakersBlock?: T | FullSpeakersBlockTypeSelect<T>;
        programBlock?: T | ProgramBlockSelect<T>;
        partnersBlock?: T | PartnersBlockSelect<T>;
        partnersGridBlock?: T | PartnersGridBlockTypeSelect<T>;
        partnerCtaBlock?: T | PartnerCtaBlockTypeSelect<T>;
        promoBannerBlock?: T | PromoBannerBlockSelect<T>;
        pressBlock?: T | PressBlockSelect<T>;
        pageBannerBlock?: T | PageBannerBlockSelect<T>;
        galleryBlock?: T | GalleryBlockSelect<T>;
        eventHighlightsBlock?: T | EventHighlightsBlockTypeSelect<T>;
        aboutBlock?: T | AboutBlockTypeSelect<T>;
        eventAgendaBlock?: T | EventAgendaBlockTypeSelect<T>;
        allPostsBlock?: T | AllPostsBlockTypeSelect<T>;
        textCardBlock?: T | TextCardBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        venueHeroBlock?: T | VenueHeroBlockTypeSelect<T>;
        venueBentoBlock?: T | VenueBentoBlockTypeSelect<T>;
        fullWidthImageBlock?: T | FullWidthImageBlockTypeSelect<T>;
        locationBlock?: T | LocationBlockTypeSelect<T>;
        partnerFormBlock?: T | PartnerFormBlockTypeSelect<T>;
        contactBlock?: T | ContactBlockTypeSelect<T>;
        allPressBlock?: T | AllPressBlockTypeSelect<T>;
        ctaButtonBlock?: T | CtaButtonBlockTypeSelect<T>;
        ctaBannerBlock?: T | CtaBannerBlockSelect<T>;
        faqBlock?: T | FAQBlockTypeSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventHeroBlock_select".
 */
export interface EventHeroBlockSelect<T extends boolean = true> {
  backgroundVideo?: T;
  subtitle?: T;
  poweredByLabel?: T;
  poweredByLogo?: T;
  eventDate?: T;
  venue?: T;
  showCountdown?: T;
  countdownDate?: T;
  countdownLabel?: T;
  ctaLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlockType_select".
 */
export interface StatsBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BentoGridBlock_select".
 */
export interface BentoGridBlockSelect<T extends boolean = true> {
  cells?:
    | T
    | {
        title?: T;
        description?: T;
        media?: T;
        cellSize?: T;
        style?: T;
        video?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HighlightsBlockType_select".
 */
export interface HighlightsBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  cards?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  tagline?: T;
  enableLink?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpeakersBlockType_select".
 */
export interface SpeakersBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  selectedSpeakers?: T;
  description?: T;
  enableLink?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpeakerHighlightBlockType_select".
 */
export interface SpeakerHighlightBlockTypeSelect<T extends boolean = true> {
  speaker?: T;
  roleLabel?: T;
  photoOverride?: T;
  quote?: T;
  heading?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FullSpeakersBlockType_select".
 */
export interface FullSpeakersBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  displayCategories?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProgramBlock_select".
 */
export interface ProgramBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  backgroundImage?: T;
  tabs?:
    | T
    | {
        label?: T;
        themeTitle?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersBlock_select".
 */
export interface PartnersBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  partnershipTypes?: T;
  enableCTA?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  strategicPartnersHeading?: T;
  strategicPartners?: T;
  poweredByText?: T;
  poweredByLogo?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersGridBlockType_select".
 */
export interface PartnersGridBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  partnershipTypes?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnerCtaBlockType_select".
 */
export interface PartnerCtaBlockTypeSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromoBannerBlock_select".
 */
export interface PromoBannerBlockSelect<T extends boolean = true> {
  logo?: T;
  dateText?: T;
  venueImage?: T;
  ctaLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PressBlock_select".
 */
export interface PressBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  enableTopLink?: T;
  topLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  bottomCards?:
    | T
    | {
        title?: T;
        description?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageBannerBlock_select".
 */
export interface PageBannerBlockSelect<T extends boolean = true> {
  backgroundImage?: T;
  subtitle?: T;
  title?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        media?: T;
        wide?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventHighlightsBlockType_select".
 */
export interface EventHighlightsBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  bulletPoints?:
    | T
    | {
        text?: T;
        id?: T;
      };
  featuredImage?: T;
  galleryImages?:
    | T
    | {
        media?: T;
        id?: T;
      };
  enableLink?: T;
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutBlockType_select".
 */
export interface AboutBlockTypeSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        image?: T;
        imagePosition?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventAgendaBlockType_select".
 */
export interface EventAgendaBlockTypeSelect<T extends boolean = true> {
  subtitleLeft?: T;
  subtitleRight?: T;
  pdfDownload?: T;
  pdfButtonLabel?: T;
  days?:
    | T
    | {
        label?: T;
        date?: T;
        title?: T;
        theme?: T;
        moderator?: T;
        sessions?:
          | T
          | {
              isTheme?: T;
              themeText?: T;
              timeStart?: T;
              timeEnd?: T;
              isBreak?: T;
              showTime?: T;
              moderator?: T;
              content?: T;
              id?: T;
            };
        tracks?:
          | T
          | {
              name?: T;
              title?: T;
              moderator?: T;
              sessions?:
                | T
                | {
                    isTheme?: T;
                    themeText?: T;
                    timeStart?: T;
                    timeEnd?: T;
                    isBreak?: T;
                    showTime?: T;
                    moderator?: T;
                    content?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AllPostsBlockType_select".
 */
export interface AllPostsBlockTypeSelect<T extends boolean = true> {
  perPage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextCardBlock_select".
 */
export interface TextCardBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VenueHeroBlockType_select".
 */
export interface VenueHeroBlockTypeSelect<T extends boolean = true> {
  backgroundImage?: T;
  overlayImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VenueBentoBlockType_select".
 */
export interface VenueBentoBlockTypeSelect<T extends boolean = true> {
  cards?:
    | T
    | {
        colSpan?: T;
        cardType?: T;
        backgroundImage?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FullWidthImageBlockType_select".
 */
export interface FullWidthImageBlockTypeSelect<T extends boolean = true> {
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LocationBlockType_select".
 */
export interface LocationBlockTypeSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  imageLink?: T;
  cards?:
    | T
    | {
        title?: T;
        content?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnerFormBlockType_select".
 */
export interface PartnerFormBlockTypeSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  descriptionLeft?: T;
  descriptionRight?: T;
  formTitle?: T;
  types?:
    | T
    | {
        value?: T;
        benefitsTitle?: T;
        benefitsDescription?: T;
        id?: T;
      };
  submitButtonText?: T;
  successTitle?: T;
  successMessage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlockType_select".
 */
export interface ContactBlockTypeSelect<T extends boolean = true> {
  detailsTitle?: T;
  detailsDescription?: T;
  address?: T;
  phone?: T;
  email?: T;
  image?: T;
  formTitle?: T;
  submitButtonText?: T;
  successTitle?: T;
  successMessage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AllPressBlockType_select".
 */
export interface AllPressBlockTypeSelect<T extends boolean = true> {
  perPage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaButtonBlockType_select".
 */
export interface CtaButtonBlockTypeSelect<T extends boolean = true> {
  link?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  alignment?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock_select".
 */
export interface CtaBannerBlockSelect<T extends boolean = true> {
  backgroundImage?: T;
  title?: T;
  subtitle?: T;
  ctaLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
        appearance?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  author?: T;
  featured?: T;
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speaker-categories_select".
 */
export interface SpeakerCategoriesSelect<T extends boolean = true> {
  title?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers_select".
 */
export interface SpeakersSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  photo?: T;
  category?: T;
  order?: T;
  bio?: T;
  longBio?: T;
  linkedinUrl?: T;
  layout?:
    | T
    | {
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        code?: T | CodeBlockSelect<T>;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock_select".
 */
export interface CodeBlockSelect<T extends boolean = true> {
  language?: T;
  code?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnership-types_select".
 */
export interface PartnershipTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  partnershipTypes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-articles_select".
 */
export interface PressArticlesSelect<T extends boolean = true> {
  title?: T;
  publicationName?: T;
  publicationLogo?: T;
  externalUrl?: T;
  date?: T;
  thumbnail?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnership-submissions_select".
 */
export interface PartnershipSubmissionsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  companyName?: T;
  type?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-submissions_select".
 */
export interface NewsletterSubmissionsSelect<T extends boolean = true> {
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        /**
         * Sub-navigation items shown in a dropdown menu.
         */
        children?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Call-to-action buttons displayed on the right side of the header.
   */
  ctaButtons?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  socialLinks?:
    | {
        platform: 'x' | 'facebook' | 'linkedin' | 'instagram' | 'tiktok' | 'youtube';
        url: string;
        id?: string | null;
      }[]
    | null;
  newsletterHeading?: string | null;
  newsletterPlaceholder?: string | null;
  newsletterSuccessMessage?: string | null;
  newsletterErrorMessage?: string | null;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  ctaLink: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
  };
  termsLink: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
  };
  privacyLink: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
    label: string;
  };
  copyright?: string | null;
  contactEmailLabel?: string | null;
  /**
   * e.g. mailto:hello@example.com
   */
  contactEmailUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  seo?: {
    siteName?: string | null;
    /**
     * Also used as the title suffix (e.g. "About Us - {siteName}").
     */
    defaultTitle?: string | null;
    defaultDescription?: string | null;
    /**
     * Recommended 1200×630. Used as the Open Graph image when a page has no SEO image.
     */
    defaultImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        children?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  ctaButtons?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  newsletterHeading?: T;
  newsletterPlaceholder?: T;
  newsletterSuccessMessage?: T;
  newsletterErrorMessage?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  ctaLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  termsLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  privacyLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  copyright?: T;
  contactEmailLabel?: T;
  contactEmailUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        siteName?: T;
        defaultTitle?: T;
        defaultDescription?: T;
        defaultImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
